# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0090146fff59777851a3009a417338b1"
name = "price-tracker"
handle = "price-tracker"
application_url = "https://interact-second-magic-technician.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-95fda48a.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://interact-second-magic-technician.trycloudflare.com/auth/callback",
  "https://interact-second-magic-technician.trycloudflare.com/auth/shopify/callback",
  "https://interact-second-magic-technician.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
